### ISSUE TITLE
Improve Repo structure

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-experiments#3]
* Merge Experiments.md into Readme.md
* List all experiments in Readme.md
* Move all Experiments in folder `/experiments`
* Move all screenshots into folder `/images`
* Move all schematics into folder `/schematics`

**Comment by mariobehling** [comment]
Move all screenshots into folder /images

The images have been moved to experiments/images instead.

**Comment by harsh-2711** [comment]
Sure @mariobehling . I will do that

**Comment by harsh-2711** [comment]
But images folder consists of three sub folders and if we shift it to /images rather than /experiments/images than we have to also change the code for displaying schematics and screenshots..

**Comment by abhinavraj23** [comment]
@mariobehling I have originally done it as it was the way the docs were kept at [pslab-desktop-app](https://github.com/fossasia/pslab-desktop-apps/tree/development/docs/_apps) repo

**Comment by mariobehling** [comment]
> But images folder consists of three sub folders and if we shift it to /images rather than /experiments/images than we have to also change the code for displaying schematics and screenshots

Yes, it needs to be changed to follow standard web practices.
